[package]
name = "math-optim-verify"
version = "0.1.0"
edition = "2021"
rust-version = "1.71"
description = "Competitive programming library checker in Rust"

[dependencies]
math-optim = { path = ".." }

[[bin]]
name = "unionfind"
path = "src/bin/data_structure/unionfind.rs"
